tables = ["Datastreams", "FeaturesOfInterest", "HistoricalLocations", "Locations", "Observations", "ObservedProperties", "Sensors", "Things"]
serverSettings = {
    "conformance": [
        "http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/thing",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/location",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/historical-location",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/datastream",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/sensor",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/observed-property",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/observation",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/feature-of-interest",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/datamodel/entity-control-information",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/resource-path",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/request-data/order",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/request-data/expand",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/request-data/select",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/request-data/orderby",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/request-data/skip",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/request-data/top",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/request-data/filter",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/request-data/built-in-filter-operations",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/create-update-delete/create-entity",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/create-update-delete/link-to-existing-entities",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/create-update-delete/deep-insert",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/create-update-delete/deep-insert-status-code",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/create-update-delete/update-entity",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/create-update-delete/delete-entity",
        "http://www.opengis.net/spec/iot_sensing/1.1/req/create-update-delete/update-entity-jsonpatch",
    ],
}
